dist: precise
sudo: required

language: python

addons:
  apt:
    sources:
      - llvm-toolchain-precise
    packages:
      - clang-format


python:
  - "3.6"
install:
  - pip install black
script:
  - black --check .
  - find . -not -path '*/\.*' | grep -E ".*\.cpp$|.*\.h$|.*\.cu$|.*\.hpp$" | xargs -I {} sh -c "diff -u <(cat {}) <(clang-format --style google {})"
