from pointnet2.models.pointnet2_msg_cls import PointNet2ClassificationMSG
from pointnet2.models.pointnet2_msg_sem import PointNet2SemSegMSG
from pointnet2.models.pointnet2_ssg_cls import PointNet2ClassificationSSG
from pointnet2.models.pointnet2_ssg_sem import PointNet2SemSegSSG
